databases:
  - name: seire
    databaseName: seire
    user: seire

services:
  - type: web
    name: seire
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: seire
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false